// OG meta frame pipeline: the share cards for a meme, a collector and a binder, plus the
// crawler-facing /m/, /u/ and /binder/ pages that point at them. The cards themselves are laid
// out in `og/cards.tsx` and rasterised by satori + resvg (`og/render.ts`); everything here is
// caching, meta tags and the SPA shell.
import { env } from './env'
import { fetchArt } from './og/art'
import { BinderCard, MemeCard, ProfileCard, type BinderSleeve } from './og/cards'
import { OG_SIZE, renderCard } from './og/render'
import { assetAgeSeconds, assetExists, assetUrl, putAsset, putAssetShortCache } from './s3'
import { getSharedSecret } from './ssm'
import { TIERS, tierFor } from '@memeon/shared/tiers'
import type { Meme } from './types'

// v6: satori cards — the foil ring, the brand type and the stat row are drawn, not composited
const ogKey = (memeId: string, tierKey: string) => `og/v6/${memeId}-${tierKey}.png`

export const OG_W = OG_SIZE.width
export const OG_H = OG_SIZE.height
/** Tier frame art, generated by `POST /api/admin/frames` and listed by `GET /api/frames`. */
export const frameKey = (tierKey: string) => `frames/${tierKey}.png`

/**
 * The brand mark every card wears: the same 20 KB every time, so a warm lambda fetches it once.
 * Only a hit is cached — a card without the mark still renders, and the next one should retry.
 */
let brandMark: string | null = null
async function logoArt(): Promise<string | null> {
  brandMark ??= await fetchArt(assetUrl('brand/memeon-logo-circle-256.png'))
  return brandMark
}

/** Six thumbnails share one card, so each gets a fraction of a hero image's budget. */
const SLEEVE_BYTES = 1536 * 1024

/**
 * Ensure the share card for (meme, tier) exists in the assets bucket and return its public URL.
 * Rendered lazily on the first request per tier, then immutable — a tier-up writes a new key.
 */
export async function ensureOgImage(meme: Meme): Promise<string> {
  const tier = tierFor(meme.reshares)
  const key = ogKey(meme.id, tier.key)
  if (await assetExists(key)) return assetUrl(key)

  const [art, logo, play] = await Promise.all([
    fetchArt(meme.imageUrl),
    logoArt(),
    // a still card cannot play, so a video says so with the badge over its first frame
    meme.mediaType === 'video' ? fetchArt(assetUrl('brand/play-overlay.png')) : null,
  ])
  const png = await renderCard(
    MemeCard({
      title: meme.title,
      reshares: meme.reshares,
      uniqueRefs: meme.uniqueRefs ?? 0,
      art,
      logo,
      play,
    }),
  )
  return putAsset(key, png, 'image/png')
}

const esc = (s: string): string =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

/**
 * Discord's inline player never loops og:video (no meta tag controls it), but
 * animated gif embeds loop endlessly. Giphy serves every rendition of a clip
 * under the same path, so the stored mp4 maps straight to its gif twin — both
 * the filename and the `rid` query param name the rendition. Null for videos
 * that didn't come from giphy (no gif exists to point at).
 */
export function giphyGifUrl(videoUrl: string): string | null {
  try {
    if (!/(^|\.)giphy\.com$/i.test(new URL(videoUrl).hostname)) return null
  } catch {
    return null
  }
  if (!/giphy\.mp4/i.test(videoUrl)) return null
  return videoUrl.replace(/giphy\.mp4/gi, 'giphy.gif')
}

function ogMetaBlock(
  meme: Meme,
  ogImageUrl: string,
  gifUrl: string | null = null,
): { title: string; block: string } {
  const tier = tierFor(meme.reshares)
  const title = `${meme.title} — ${tier.name.toUpperCase()} ${tier.rarity}`
  const desc = `${meme.reshares.toLocaleString()} views · ${(meme.uniqueRefs ?? 0).toLocaleString()} reshares · ${tier.hype} Collect, trade, and invest on MemeOn.`
  const pageUrl = `${env.siteOrigin}/m/${meme.id}`
  const video = !gifUrl && meme.mediaType === 'video' && meme.videoUrl
  // gif embed (Discord): the raw animated gif replaces the branded card and the
  // player so the client loops it; its dimensions aren't the card's, so omit them
  const image = gifUrl
    ? `<meta property="og:image" content="${esc(gifUrl)}">\n<meta property="og:image:type" content="image/gif">`
    : `<meta property="og:image" content="${esc(ogImageUrl)}">\n<meta property="og:image:width" content="${OG_W}">\n<meta property="og:image:height" content="${OG_H}">`
  const block = `<meta property="og:site_name" content="MemeOn">
<meta property="og:type" content="website">
<meta property="og:url" content="${esc(pageUrl)}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(desc)}">
${image}
${video ? `<meta property="og:video" content="${esc(meme.videoUrl!)}">\n<meta property="og:video:type" content="video/mp4">\n` : ''}<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(title)}">
<meta name="twitter:description" content="${esc(desc)}">
<meta name="twitter:image" content="${esc(gifUrl ?? ogImageUrl)}">
<meta name="theme-color" content="${tier.color}">`
  return { title, block }
}

// The SPA's index.html, fetched through the site origin and cached briefly per
// warm lambda (its asset hashes change on deploy; index is served max-age=60).
let indexCache: { html: string; at: number } | null = null

async function fetchIndexHtml(): Promise<string | null> {
  if (indexCache && Date.now() - indexCache.at < 60_000) return indexCache.html
  try {
    const res = await fetch(`${env.siteOrigin}/index.html`, {
      headers: { accept: 'text/html' },
    })
    if (!res.ok) return indexCache?.html ?? null
    const html = await res.text()
    indexCache = { html, at: Date.now() }
    return html
  } catch {
    return indexCache?.html ?? null
  }
}

/**
 * The page served at a meme's share URL (/m/{id}). Crawlers read the injected
 * og tags; humans get the full SPA at this same URL — it never redirects, so
 * copying the address bar re-shares the counting /m/ link.
 */
export async function memePageHtml(
  meme: Meme,
  ogImageUrl: string,
  opts: { loopingGif?: boolean } = {},
): Promise<string> {
  const gifUrl =
    opts.loopingGif && meme.mediaType === 'video' && meme.videoUrl
      ? giphyGifUrl(meme.videoUrl)
      : null
  const { title, block } = ogMetaBlock(meme, ogImageUrl, gifUrl)
  const index = await fetchIndexHtml()
  if (index) {
    return index
      // drop the site-wide og/twitter tags — crawlers honor the first tag seen
      .replace(/\s*<meta (?:property="og:|name="twitter:)[^>]*\/?>/g, '')
      .replace(/<title>[^<]*<\/title>/, `<title>${esc(title)}</title>`)
      .replace('</head>', `${block}\n</head>`)
  }
  // fallback when the SPA shell can't be fetched: og tags + a manual link
  const appUrl = `/m/${encodeURIComponent(meme.id)}`
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${esc(title)}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
${block}
</head>
<body>
<p>${esc(title)} · <a href="${esc(appUrl)}">open on MemeOn</a></p>
</body>
</html>`
}

/**
 * Collector share card: avatar, name and the two numbers that describe a collection.
 * Cached in S3, refreshed when older than an hour (stats drift).
 */
export async function ensureProfileOgImage(profile: {
  sub: string
  name: string
  picture: string | null
  coins: number
  collectionSize: number
}): Promise<string> {
  const key = `og/u/${profile.sub}.png`
  const age = await assetAgeSeconds(key)
  if (age !== null && age < 3600) return assetUrl(key)

  const [avatar, logo] = await Promise.all([
    profile.picture ? fetchArt(profile.picture) : null,
    logoArt(),
  ])
  const png = await renderCard(
    ProfileCard({
      name: profile.name,
      coins: profile.coins,
      collectionSize: profile.collectionSize,
      avatar,
      logo,
    }),
  )
  await putAssetShortCache(key, png)
  return assetUrl(key)
}

/**
 * SPA shell with profile og tags injected (crawlers see the person; humans
 * get the app at the same URL).
 */
export async function profilePageHtml(
  profile: { sub: string; name: string; coins: number; collectionSize: number },
  ogImageUrl: string,
): Promise<string> {
  const title = `${profile.name} on MemeOn`
  const desc = `🧠 ${profile.coins.toLocaleString()} braincells · ${profile.collectionSize} memes in the binder. Collect, trade, and invest in memes on MemeOn.`
  const pageUrl = `${env.siteOrigin}/u/${encodeURIComponent(profile.sub)}`
  const block = `<meta property="og:site_name" content="MemeOn">
<meta property="og:type" content="profile">
<meta property="og:url" content="${esc(pageUrl)}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(desc)}">
<meta property="og:image" content="${esc(ogImageUrl)}">
<meta property="og:image:width" content="${OG_W}">
<meta property="og:image:height" content="${OG_H}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(title)}">
<meta name="twitter:image" content="${esc(ogImageUrl)}">`
  const index = await fetchIndexHtml()
  if (index) {
    return index
      .replace(/\s*<meta (?:property="og:|name="twitter:)[^>]*\/?>/g, '')
      .replace(/<title>[^<]*<\/title>/, `<title>${esc(title)}</title>`)
      .replace('</head>', `${block}\n</head>`)
  }
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title>${block}</head><body><a href="${esc(pageUrl)}">${esc(title)}</a></body></html>`
}

/** The SPA shell as-is — for share-path URLs that aren't a real user (e.g. /binder/new). */
export async function spaShellHtml(): Promise<string> {
  const index = await fetchIndexHtml()
  if (index) return index
  return `<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=${esc(env.siteOrigin)}"></head><body></body></html>`
}

/**
 * Binder share card: the collector on the left, their highest-value cards sleeved on the right.
 * Cached in S3, refreshed when older than an hour (stats drift).
 */
export async function ensureBinderOgImage(
  profile: { sub: string; name: string; picture: string | null },
  stats: { collectionSize: number; value: number },
  topMemes: Meme[],
): Promise<string> {
  const key = `og/binder/${profile.sub}.png`
  const age = await assetAgeSeconds(key)
  if (age !== null && age < 3600) return assetUrl(key)

  const [avatar, logo, sleeves] = await Promise.all([
    profile.picture ? fetchArt(profile.picture) : null,
    logoArt(),
    Promise.all(
      topMemes.slice(0, 6).map(
        async (meme): Promise<BinderSleeve> => ({
          tier: tierFor(meme.reshares),
          art: await fetchArt(meme.imageUrl, SLEEVE_BYTES),
        }),
      ),
    ),
  ])
  const png = await renderCard(
    BinderCard({
      name: profile.name,
      collectionSize: stats.collectionSize,
      value: stats.value,
      avatar,
      logo,
      sleeves,
    }),
  )
  await putAssetShortCache(key, png)
  return assetUrl(key)
}

/** SPA shell with binder og tags injected (crawlers see the collection; humans get the app). */
export async function binderPageHtml(
  profile: { sub: string; name: string },
  stats: { collectionSize: number; value: number },
  topMeme: Meme | undefined,
  ogImageUrl: string,
): Promise<string> {
  const title = `${profile.name}'s Meme Binder`
  const topLine = topMeme
    ? ` Top card: "${topMeme.title}" (${tierFor(topMeme.reshares).name.toUpperCase()}).`
    : ''
  const desc = `${stats.collectionSize} memes worth 🧠 ${stats.value.toLocaleString()} braincells.${topLine} Browse the collection on MemeOn.`
  const pageUrl = `${env.siteOrigin}/binder/${encodeURIComponent(profile.sub)}`
  const block = `<meta property="og:site_name" content="MemeOn">
<meta property="og:type" content="website">
<meta property="og:url" content="${esc(pageUrl)}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(desc)}">
<meta property="og:image" content="${esc(ogImageUrl)}">
<meta property="og:image:width" content="${OG_W}">
<meta property="og:image:height" content="${OG_H}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(title)}">
<meta name="twitter:description" content="${esc(desc)}">
<meta name="twitter:image" content="${esc(ogImageUrl)}">`
  const index = await fetchIndexHtml()
  if (index) {
    return index
      .replace(/\s*<meta (?:property="og:|name="twitter:)[^>]*\/?>/g, '')
      .replace(/<title>[^<]*<\/title>/, `<title>${esc(title)}</title>`)
      .replace('</head>', `${block}\n</head>`)
  }
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title>${block}</head><body><a href="${esc(pageUrl)}">${esc(title)}</a></body></html>`
}

/**
 * Ask Facebook to re-scrape a page (busts its ~30-day og cache) — fired on
 * tier-ups so old shares upgrade their card. Silently skipped unless
 * /memeon/shared/facebook_app_token (APP_ID|APP_SECRET) exists.
 */
export async function pingFacebookRescrape(pageUrl: string): Promise<void> {
  let token: string
  try {
    token = await getSharedSecret('facebook_app_token')
  } catch {
    return
  }
  await fetch(
    `https://graph.facebook.com/v19.0/?id=${encodeURIComponent(pageUrl)}&scrape=true&access_token=${encodeURIComponent(token)}`,
    { method: 'POST', signal: AbortSignal.timeout(4000) },
  ).catch(() => {})
}

export function tierFrameList(): { key: string; name: string; url: string }[] {
  return TIERS.map((t) => ({ key: t.key, name: t.name, url: assetUrl(frameKey(t.key)) }))
}
