import type { CreateMemeContext } from '../../stores/createMemeMachine'

export const baseCreateMemeContext: CreateMemeContext = {
  remixId: null,
  mode: 'generate',
  remixSource: null,
  remixOutput: 'image',
  videoMode: 'edit',
  motionPrompt: '',
  editedFrame: null,
  title: 'title',
  tags: 'chaos',
  prompt: 'capybara',
  urlDraft: '',
  imageUrl: '/thumb.png',
  videoUrl: '',
  imageFileName: null,
  videoFileName: null,
  busy: null,
  busyElapsed: null,
  err: null,
  giphyCategories: [],
  giphyQuery: '',
  giphyResults: [],
  giphySearched: false,
  giphyPick: null,
  edited: false,
  artworkSource: null,
  mintedId: null,
  shareUrl: '',
  shareCopied: false,
  shareCopyFailed: false,
}
