/** Auto-generated by web/scripts/sync-storybook-memes.mjs — do not edit by hand. */
export const devMemeMedia = {
  "frames": {
    "paper": "https://memeon-assets-dev.s3.us-west-2.amazonaws.com/frames/paper.png",
    "silver": "https://memeon-assets-dev.s3.us-west-2.amazonaws.com/frames/silver.png",
    "holo": "https://memeon-assets-dev.s3.us-west-2.amazonaws.com/frames/holo.png",
    "chrome": "https://memeon-assets-dev.s3.us-west-2.amazonaws.com/frames/chrome.png",
    "gold": "https://memeon-assets-dev.s3.us-west-2.amazonaws.com/frames/gold.png",
    "prismatic": "https://memeon-assets-dev.s3.us-west-2.amazonaws.com/frames/prismatic.png",
    "shiny": "https://memeon-assets-dev.s3.us-west-2.amazonaws.com/frames/shiny.png"
  },
  "roles": {
    "paper": {
      "id": "8609e3e7-f30",
      "title": "Procrastination Sloth",
      "imageUrl": "https://firebasestorage.googleapis.com/v0/b/maskydotnet.firebasestorage.app/o/userData%2Ftwitch_11867613%2Fimages%2Fimg_1783377084496_f6f27acd.jpeg?alt=media&token=5624e826acd057cea813e974faf22508",
      "videoUrl": null,
      "reshares": 1,
      "tierKey": "paper",
      "listing": null,
      "creatorId": "memeon_vault",
      "creatorName": "MemeOn Vault",
      "ownerId": "memeon_vault",
      "ownerName": "MemeOn Vault",
      "mediaType": "image"
    },
    "silver": {
      "id": "359c6d6a-6fb",
      "title": "pushrax",
      "imageUrl": "https://firebasestorage.googleapis.com/v0/b/maskydotnet.firebasestorage.app/o/userData%2Ftwitch_11867613%2Fimages%2Fimg_1785570788758_28711994.jpeg?alt=media&token=d85569f1b0565c1bf93fc1db993e0c47",
      "videoUrl": null,
      "reshares": 19,
      "tierKey": "silver",
      "listing": {
        "pricePerShare": 1,
        "sellerId": "ava_3bb42eef612070f99e4ae967",
        "shares": 8
      },
      "creatorId": "ava_3bb42eef612070f99e4ae967",
      "creatorName": "CyberSeth",
      "ownerId": "ava_3bb42eef612070f99e4ae967",
      "ownerName": "CyberSeth",
      "mediaType": "image"
    },
    "holo": {
      "id": "33d2086f-bbb",
      "title": "Doomscroll Hamster",
      "imageUrl": "https://firebasestorage.googleapis.com/v0/b/maskydotnet.firebasestorage.app/o/userData%2Ftwitch_11867613%2Fimages%2Fimg_1783377034571_ebe51af3.jpeg?alt=media&token=3cdc940d5e0cffcfb274920db72e3713",
      "videoUrl": null,
      "reshares": 75,
      "tierKey": "holo",
      "listing": null,
      "creatorId": "memeon_vault",
      "creatorName": "MemeOn Vault",
      "ownerId": "memeon_vault",
      "ownerName": "MemeOn Vault",
      "mediaType": "image"
    },
    "chrome": {
      "id": "3ee60644-f24",
      "title": "Cat.exe Has Stopped",
      "imageUrl": "https://firebasestorage.googleapis.com/v0/b/maskydotnet.firebasestorage.app/o/userData%2Ftwitch_11867613%2Fimages%2Fimg_1783377076532_91133873.jpeg?alt=media&token=17b1760cd6d5bdf84427e7a08ebfbbe1",
      "videoUrl": null,
      "reshares": 400,
      "tierKey": "chrome",
      "listing": null,
      "creatorId": "memeon_vault",
      "creatorName": "MemeOn Vault",
      "ownerId": "memeon_vault",
      "ownerName": "MemeOn Vault",
      "mediaType": "image"
    },
    "gold": {
      "id": "d658a6e8-428",
      "title": "jim carey idea jobs",
      "imageUrl": "https://memeon-assets-dev.s3.us-west-2.amazonaws.com/uploads/ava_3bb42eef612070f99e4ae967/804d30b7-491d-4f81-ace1-caff75016a35.jpg",
      "videoUrl": null,
      "reshares": 1514,
      "tierKey": "gold",
      "listing": null,
      "creatorId": "ava_3bb42eef612070f99e4ae967",
      "creatorName": "CyberSeth",
      "ownerId": "ava_3bb42eef612070f99e4ae967",
      "ownerName": "CyberSeth",
      "mediaType": "image"
    },
    "shiny": {
      "id": "e85670e9-ef8",
      "title": "John Brennan riding a red rocket",
      "imageUrl": "https://firebasestorage.googleapis.com/v0/b/maskydotnet.firebasestorage.app/o/userData%2Ftwitch_11867613%2Fimages%2Fimg_1783374474231_2eb4f986.jpeg?alt=media&token=dfa69a85d5a2c57ac1aaa94d357904cb",
      "videoUrl": null,
      "reshares": 30000,
      "tierKey": "shiny",
      "listing": null,
      "creatorId": "ava_3bb42eef612070f99e4ae967",
      "creatorName": "CyberSeth",
      "ownerId": "ava_3bb42eef612070f99e4ae967",
      "ownerName": "CyberSeth",
      "mediaType": "image"
    },
    "listed": {
      "id": "359c6d6a-6fb",
      "title": "pushrax",
      "imageUrl": "https://firebasestorage.googleapis.com/v0/b/maskydotnet.firebasestorage.app/o/userData%2Ftwitch_11867613%2Fimages%2Fimg_1785570788758_28711994.jpeg?alt=media&token=d85569f1b0565c1bf93fc1db993e0c47",
      "videoUrl": null,
      "reshares": 19,
      "tierKey": "silver",
      "listing": {
        "pricePerShare": 1,
        "sellerId": "ava_3bb42eef612070f99e4ae967",
        "shares": 8
      },
      "creatorId": "ava_3bb42eef612070f99e4ae967",
      "creatorName": "CyberSeth",
      "ownerId": "ava_3bb42eef612070f99e4ae967",
      "ownerName": "CyberSeth",
      "mediaType": "image"
    },
    "video": {
      "id": "5da7b1a3-c6e",
      "title": "happy d&d",
      "imageUrl": "https://media4.giphy.com/media/v1.Y2lkPTNiNDcyMmJhaWtxbTc0cHhxNjZ2c2dncnU2bDJpYmQ5MTd3c3d6cnF3b2oxczNoNCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/14uQCRCYbcm6jPvWZp/giphy-downsized_s.gif",
      "videoUrl": "https://media4.giphy.com/media/v1.Y2lkPTNiNDcyMmJhaWtxbTc0cHhxNjZ2c2dncnU2bDJpYmQ5MTd3c3d6cnF3b2oxczNoNCZlcD12MV9naWZzX3NlYXJjaCZjdD1n/14uQCRCYbcm6jPvWZp/giphy.mp4",
      "reshares": 0,
      "tierKey": "paper",
      "listing": {
        "shares": 100,
        "sellerId": "meme_archive",
        "pricePerShare": 0.1
      },
      "creatorId": "meme_archive",
      "creatorName": "Meme Archive",
      "ownerId": "meme_archive",
      "ownerName": "Meme Archive",
      "mediaType": "video"
    },
    "prismatic": {
      "id": "d658a6e8-428-prismatic-demo",
      "title": "jim carey idea jobs",
      "imageUrl": "https://memeon-assets-dev.s3.us-west-2.amazonaws.com/uploads/ava_3bb42eef612070f99e4ae967/804d30b7-491d-4f81-ace1-caff75016a35.jpg",
      "videoUrl": null,
      "reshares": 5000,
      "tierKey": "prismatic",
      "listing": null,
      "creatorId": "ava_3bb42eef612070f99e4ae967",
      "creatorName": "CyberSeth",
      "ownerId": "ava_3bb42eef612070f99e4ae967",
      "ownerName": "CyberSeth",
      "mediaType": "image"
    }
  }
} as const
